version: '3.5'

services:
  app:
    build: .
    restart: always
    command: 'yarn start:dev'
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/app/src

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db

volumes:
  mongo:
