version: '3.5'

services:
  app:
    build: .
    restart: always
    command: 'yarn start:dev'
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/app/src

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"

volumes:
  mongo:
